import localFont from "next/font/local";
import "./globals.css";
import Nav from "./Components/Nav";
import Search from "./Components/Search";
import UserNav from "./Components/Foryou/UserNav";
import Footer from "./Components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const logged = true;

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {logged ? (
          <>
            <Search />
            <UserNav />
          </>
        ) : null}
        {children}

      </body>
    </html>
  );
}
